CREATE TABLE t1(i INT PRIMARY KEY) $$
INSERT INTO t1 VALUES (1), (2);

BEGIN;
INSERT INTO t1 VALUES (2);
INSERT INTO t1 VALUES (3);
COMMIT;
SELECT * FROM t1;

BEGIN;
REPLACE INTO t1 VALUES (2);
INSERT INTO t1 VALUES (3);
COMMIT;
SELECT * FROM t1;

REPLACE INTO t1 VALUES (1), (2), (3), (4);
SELECT * FROM t1;

CREATE TABLE t2(i INT PRIMARY KEY, c CSTRING(100)) $$
INSERT INTO t2 VALUES (1, "aaa"), (2, "bbb");

BEGIN;
REPLACE INTO t2 VALUES (1, "ccc"), (2, "ddd");
INSERT INTO t2 VALUES (1, "ccc"), (2, "ddd");
COMMIT;
SELECT * FROM t2;

REPLACE INTO t2 VALUES (1, "ccc"), (2, "ddd");
SELECT * FROM t2;

DROP TABLE t1;
DROP TABLE t2;

exec procedure sys.cmd.send('verify t1');
